### ISSUE TITLE
No bot update for 27.1

### ISSUE THREAD

**Issue by asmeurer** [conda-forge/emacs-feedstock#42]
@conda-forge/bot the bot did updates for this feedstock in the past, but it hasn't made any PRs for the latest 27.1 release.

**Comment by CJ-Wright** [comment]
Hmm, was there a 27.0 release?

**Comment by asmeurer** [comment]
Looks like there wasn't https://ftp.gnu.org/gnu/emacs/

**Comment by beckermr** [comment]
bot doesn't like skipped versions...

**Comment by CJ-Wright** [comment]
So we currently try to increment all the numbers in the version, but set the lower numbers to zero for sources that don't otherwise provide an API for getting the latest version. If that version doesn't exist then we don't find it.

If you want the code that manages this is [here](https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/update_sources.py#L379) I would be interested in a PR that fixes this without slowing down the bot too much

**Comment by asmeurer** [comment]
Looking at the URL I posted, it looks like emacs never uses `.0`. So maybe it needs to be special-cased to look for `.1`.

**Comment by asmeurer** [comment]
Maybe here it should try both .0 and .1. https://github.com/regro/cf-scripts/blob/e7a0d6edf3e7234518e064ced3c80857e11ac106/conda_forge_tick/update_sources.py#L81-L89. I don't know if it's too much to try that in general, or if it should just try to special-case known packages that do this.

**Comment by beckermr** [comment]
Right @asmeurer. We can add some number of increments to the code. This will end up making the version checks slower very quickly though.

**Comment by asmeurer** [comment]
I think this is working now.
